### ISSUE TITLE
Can't run polis cli

### ISSUE THREAD

**Issue by strogiyotec** [polispay/polis#70] opened 2018-12-25 05:40 UTC
I download the latest tag of POLIS (1.4.7) when I run polisd (Ubuntu 16.04) I got the following error

./polisd: 1: ./polisd: ELF��u: not found
./polisd: 2: ./polisd: Syntax error: word unexpected (expecting ")")

How to fix it?

**Comment by eabz** [comment] 2019-01-14 02:06
@strogiyotec Can you confirm you are still having the issue?
Sometimes the issue is on the program you use to monitor the node. A reboot may fix it.

**Comment by Lollipopster** [comment] 2019-01-14 10:00
@eabz You close this ticket , thank you for helping

**Comment by strogiyotec** [comment] 2019-01-14 10:08
@eabz You can close this ticket , thank you for helping

**Closed** 2019-01-14 16:19 UTC
