### ISSUE TITLE
[Qt] Linux Wallets not accepting keyboard Input on some distros

### ISSUE THREAD

**Issue by PrettyBoyHelios** [polispay/polis#55] opened 2018-10-31 15:39 UTC
### Describe the issue
Linux wallet not accepting keyboard input on some linux distros, namely Kubuntu 18.04.  

### Expected behaviour
Keyboard should work.

### Actual behaviour
It doesn't.

### Screenshots.
```shell
$ ./polis-qt 
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```

### What version of Polis Core are you using?
PolisCore v1.4.5, likely since v1.4.3.

### Machine specs:
- OS: Kubuntu 18.04

### Any extra information that might be useful in the debugging process.
User solved the problem by adding a PATH variable.  
```shell
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
```
It's a known Qt issue.

[Qt Issues](https://bugreports.qt.io/browse/QTBUG-56227)

**Comment by PrettyBoyHelios** [comment] 2018-12-03 20:19
Wasn't included due to compilation issues, it is still planned for 1.4.7.1 or 1.4.8, whichever comes first.

**Comment by developery-nl** [comment] 2019-01-10 00:17
Same issue. Using Linux 16.04 (Mint / Sonya distr)

**Comment by eabz** [comment] 2019-01-14 02:02
Will close this. Confirmed to be solved on codebase.

**Closed by eabz** 2019-01-14 02:02 UTC
Labels: bug

**Comment by jealcalat** [comment] 2019-05-14 06:53
I have Qt 5.9.7, in Manjaro version 4.19 the problem is persistent. 

```
Qt 5.9.7 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0) on "xcb" 
OS: Manjaro Linux [linux version 4.19.36-1-MANJARO]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:
  QT_QPA_PLATFORMTHEME="qt5ct"
  QT_XKB_CONFIG_ROOT="/usr/share/X11/xkb"

Features: QT_NO_EXCEPTIONS

```
